[package]
name = "redis-server-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
wasmedge-sdk = {git = "https://github.com/oss-fun/wasmedge-rust-sdk.git", branch = "v0.9.0"}
